### ISSUE TITLE
Not Able to Set Date Field

### ISSUE THREAD

**Issue by amitprajapati2298** [DigitalFlow/D365-UI-Test#3]
Hi @DigitalFlow ,
I m using this UI Framework for the Test Automation. But when I was trying to set the Date Value on the D365 CRM Entity Date Field then My Test Failed every time. Can you please let me know how to set the Date Field. Is there is functionality available or not.

**Comment by amitprajapati2298** [comment]
> Hi @DigitalFlow ,
> I m using this UI Framework for the Test Automation. But when I was trying to set the Date Value on the D365 CRM Entity Date Field then My Test Failed every time. Can you please let me know how to set the Date Field. Is there is functionality available or not.

**Comment by DigitalFlow** [comment]
Hi @amitprajapati2298,

thanks for reaching out.
All field types are supported. I will check at my side and return to you with results on how to use it or flag it as bug.

Kind Regards,
Florian

**Comment by DigitalFlow** [comment]
Hi @amitprajapati2298 
As it turns out, this was a bug.
Can you please install v0.0.38 and check if it works for you now?

**Comment by DigitalFlow** [comment]
Hi @amitprajapati2298,

did you check if it works for you now?

**Comment by amitprajapati2298** [comment]
Hi,

Yes, I have checked that it is working correctly.

I have tried to create a record with the date field so I was able to set the date field and save the record.

**Comment by amitprajapati2298** [comment]
Thank you for updating the Code because is not of the most critical field. And After the update, I'm able to set the date in the CRM Date Fields.

**Comment by DigitalFlow** [comment]
Hi @amitprajapati2298,

Thanks for your response, I'm glad it works for you.
Just out of curiosity, how was your experience with this lib until now?
Do you cover some advanced test scenarios, where the existing functionalities did not suffice?
Did you get everything to work as you expected with reasonable time effort needed?

This was the core goal of this library and it's doing what it should for me, but some external feedback would be valuable as well.

Kind Regards,
Florian
